# Generated by Django 5.1.6 on 2025-04-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('sal', models.FloatField()),
                ('sex', models.CharField(max_length=6)),
                ('dno', models.IntegerField()),
            ],
        ),
    ]
